version: "3.8"

services:
  app:
    container_name: car_rental_app
    build: .
    ports:
      - "4000:3000"
    environment:
      DATABASE_URL: "postgresql://admin40:admin40@db:5432/car_rental?schema=public"
    depends_on:
      - db

  db:
    container_name: car_rental_db
    image: postgres:latest
    restart: always
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=admin40
      - POSTGRES_PASSWORD=admin40
      - POSTGRES_DB=car_rental
    volumes:
      - /var/lib/postgresql/data

volumes:
  db_data:
