name: Deploy to VPS

on:
  push:
    branches:
      - backup

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            caddy start
            cd BackEnd_Practice_EXpress/
            docker compose up
